title: "Buttons"
description: |
  Buttons should be used in situations where an obvious action is required. They should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      This is the default button. It should always be used first.
    fields:
      - name: url
        type: url
        example: "/products/"
      - name: text
        type: string
        example: "Shop now"
  ghost:
    title: "Ghost"
    description: |
      This is the secondary button. It should be used to add variation to the design.
